-- schema.sql

-- Create User table
CREATE TABLE IF NOT EXISTS User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL
);

-- Create Post table
CREATE TABLE IF NOT EXISTS Post (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  userId INT,
  FOREIGN KEY (userId) REFERENCES User(id)
);

-- Create Comment table
CREATE TABLE IF NOT EXISTS Comment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  userId INT,
  postId INT,
  FOREIGN KEY (userId) REFERENCES User(id),
  FOREIGN KEY (postId) REFERENCES Post(id)
);
